#!/bin/bash

while getopts i:o: option
do
case "${option}"
in
i) IN_DIR=${OPTARG};;
o) OUT_DIR=${OPTARG};;
esac
done

mkdir -p OUT_DIR

docker-compose -f ../Docker/docker-compose.base.prod.yml -f ../Docker/docker-compose.application.prod.yml run -e IN_DIR="${IN_DIR}" -e OUT_DIR="${OUT_DIR}" searchengine