version: '3.1'

services:
    mongo-seed:
        build:
            context: ./
            dockerfile: ./mongoseed.prod.Dockerfile
        volumes:
            - ../argument_ndjson/:/argument_ndjson/
        networks:
            - bridge_network
        depends_on:
            - mongo