version: '3.1'

services:
    searchengine:
        build:
            context: ..
            dockerfile: Docker/Dockerfile
        networks:
            - bridge_network
        depends_on:
            - mongo
        env_file:
            - ../.env
        environment:
            - ENV=PROD
        volumes:
            - /tmp:/tmp
            - /media:/media
            - ../index:/usr/peyrer/index
            - /usr/peyrer/tempIndex