# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:4.2
    restart: always
    volumes:
      - ../argument_ndjson:/argument_ndjson
    networks:
      - bridge_network
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:0.54
    restart: always
    networks:
      - bridge_network
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  #searchengine:
    #build:
      #context: ..
      #dockerfile: Docker/Dockerfile

networks:
  bridge_network:
    driver: bridge


