version: '3.1'

services:
    mongo-seed:
        build:
            context: ../argument_ndjson/
            dockerfile: ../Docker/mongoseed.prod.Dockerfile
        networks:
            - bridge_network
        depends_on:
            - mongo